import { MediaItem, TVSeason, TVEpisode, Genre } from '../types';

export const MOVIE_GENRES: Genre[] = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Adventure' },
  { id: 16, name: 'Animation' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 99, name: 'Documentary' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Family' },
  { id: 14, name: 'Fantasy' },
  { id: 36, name: 'History' },
  { id: 27, name: 'Horror' },
  { id: 10402, name: 'Music' },
  { id: 9648, name: 'Mystery' },
  { id: 10749, name: 'Romance' },
  { id: 878, name: 'Sci-Fi' },
  { id: 53, name: 'Thriller' },
  { id: 10752, name: 'War' },
];

export const TV_GENRES: Genre[] = [
  { id: 10759, name: 'Action & Adventure' },
  { id: 16, name: 'Animation' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 99, name: 'Documentary' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Family' },
  { id: 10762, name: 'Kids' },
  { id: 9648, name: 'Mystery' },
  { id: 10765, name: 'Sci-Fi & Fantasy' },
  { id: 10768, name: 'War & Politics' },
];

export const FALLBACK_MOVIES: MediaItem[] = [
  {
    id: 693134,
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5200fr.jpg',
    media_type: 'movie',
    release_date: '2024-02-27',
    vote_average: 8.2,
    vote_count: 5800,
    genre_ids: [878, 12],
    popularity: 924.5,
    runtime: 166,
    tagline: 'Long live the fighters.',
    status: 'Released',
  },
  {
    id: 533535,
    title: 'Deadpool & Wolverine',
    original_title: 'Deadpool & Wolverine',
    overview: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
    poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop_path: '/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg',
    media_type: 'movie',
    release_date: '2024-07-24',
    vote_average: 7.7,
    vote_count: 4900,
    genre_ids: [28, 35, 878],
    popularity: 880.2,
    runtime: 128,
    tagline: 'Come together.',
    status: 'Released',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    media_type: 'movie',
    release_date: '2023-07-19',
    vote_average: 8.1,
    vote_count: 8900,
    genre_ids: [18, 36],
    popularity: 430.8,
    runtime: 181,
    tagline: 'The world forever changes.',
    status: 'Released',
  },
  {
    id: 569094,
    title: 'Spider-Man: Across the Spider-Verse',
    original_title: 'Spider-Man: Across the Spider-Verse',
    overview: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence.',
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    media_type: 'movie',
    release_date: '2023-05-31',
    vote_average: 8.4,
    vote_count: 7200,
    genre_ids: [16, 28, 12, 878],
    popularity: 380.5,
    runtime: 140,
    tagline: 'It’s how you wear the mask that matters.',
    status: 'Released',
  },
  {
    id: 157336,
    title: 'Interstellar',
    original_title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/rAiYTApp0inxdHDujUtmrJbpqjs.jpg',
    media_type: 'movie',
    release_date: '2014-11-05',
    vote_average: 8.4,
    vote_count: 35000,
    genre_ids: [12, 18, 878],
    popularity: 310.2,
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    status: 'Released',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    original_title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    media_type: 'movie',
    release_date: '2008-07-16',
    vote_average: 8.5,
    vote_count: 32000,
    genre_ids: [18, 28, 80, 53],
    popularity: 290.7,
    runtime: 152,
    tagline: 'Why So Serious?',
    status: 'Released',
  },
  {
    id: 414906,
    title: 'The Batman',
    original_title: 'The Batman',
    overview: 'In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.',
    poster_path: '/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdrop_path: '/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
    media_type: 'movie',
    release_date: '2022-03-01',
    vote_average: 7.7,
    vote_count: 10200,
    genre_ids: [80, 9648, 53],
    popularity: 250.0,
    runtime: 176,
    tagline: 'Unmask the truth.',
    status: 'Released',
  },
  {
    id: 27205,
    title: 'Inception',
    original_title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    media_type: 'movie',
    release_date: '2010-07-15',
    vote_average: 8.4,
    vote_count: 36000,
    genre_ids: [28, 878, 12],
    popularity: 220.4,
    runtime: 148,
    tagline: 'Your mind is the scene of the crime.',
    status: 'Released',
  },
  {
    id: 558449,
    title: 'Gladiator II',
    original_title: 'Gladiator II',
    overview: 'Years after witnessing the death of revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after the powerful emperors of Rome conquer his home.',
    poster_path: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdrop_path: '/euYIwmwkmz95mnXvufEmbL69ovr.jpg',
    media_type: 'movie',
    release_date: '2024-11-13',
    vote_average: 6.8,
    vote_count: 2400,
    genre_ids: [28, 12, 18],
    popularity: 580.0,
    runtime: 148,
    tagline: 'What we do in life echoes in eternity.',
    status: 'Released',
  },
  {
    id: 76600,
    title: 'Avatar: The Way of Water',
    original_title: 'Avatar: The Way of Water',
    overview: 'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    backdrop_path: '/8rpDcsfLJypbO6vREc0547VKqEv.jpg',
    media_type: 'movie',
    release_date: '2022-12-14',
    vote_average: 7.6,
    vote_count: 11500,
    genre_ids: [878, 12, 28],
    popularity: 310.0,
    runtime: 192,
    tagline: 'Return to Pandora.',
    status: 'Released',
  },
];

export const FALLBACK_TV_SHOWS: MediaItem[] = [
  {
    id: 66732,
    name: 'Stranger Things',
    original_name: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    media_type: 'tv',
    first_air_date: '2016-07-15',
    vote_average: 8.6,
    vote_count: 17200,
    genre_ids: [10765, 18, 9648],
    popularity: 850.3,
    number_of_seasons: 4,
    number_of_episodes: 34,
    tagline: 'Every ending has a beginning.',
    status: 'Returning Series',
  },
  {
    id: 100088,
    name: 'The Last of Us',
    original_name: 'The Last of Us',
    overview: 'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the U.S. and depend on each other for survival.',
    poster_path: '/uKvVjHNqB5VmOrdxqAt2V7JMrHE.jpg',
    backdrop_path: '/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    media_type: 'tv',
    first_air_date: '2023-01-15',
    vote_average: 8.6,
    vote_count: 5100,
    genre_ids: [18, 10759, 10765],
    popularity: 720.0,
    number_of_seasons: 1,
    number_of_episodes: 9,
    tagline: 'When you’re lost in the darkness, look for the light.',
    status: 'Returning Series',
  },
  {
    id: 94997,
    name: 'House of the Dragon',
    original_name: 'House of the Dragon',
    overview: 'The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights. In the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne.',
    poster_path: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
    backdrop_path: '/etj5CuMuamBSpRnZqAdDXq7xyT.jpg',
    media_type: 'tv',
    first_air_date: '2022-08-21',
    vote_average: 8.4,
    vote_count: 4600,
    genre_ids: [10765, 18, 10759],
    popularity: 640.4,
    number_of_seasons: 2,
    number_of_episodes: 18,
    tagline: 'All must choose.',
    status: 'Returning Series',
  },
  {
    id: 94605,
    name: 'Arcane',
    original_name: 'Arcane',
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    poster_path: '/abf8tHznhSvl9BAElD23cQOGjqW.jpg',
    backdrop_path: '/fqv8v6AycXKsivp1T5yKtLbGXce.jpg',
    media_type: 'tv',
    first_air_date: '2021-11-06',
    vote_average: 8.8,
    vote_count: 4200,
    genre_ids: [16, 10765, 10759, 18],
    popularity: 610.1,
    number_of_seasons: 2,
    number_of_episodes: 18,
    tagline: 'Every legend has a beginning.',
    status: 'Ended',
  },
  {
    id: 1396,
    name: 'Breaking Bad',
    original_name: 'Breaking Bad',
    overview: 'Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He decides he has nothing to lose and decides to enter the dangerous world of drugs and crime and meth manufacturing to ensure his family\'s financial future.',
    poster_path: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop_path: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    media_type: 'tv',
    first_air_date: '2008-01-20',
    vote_average: 8.9,
    vote_count: 14000,
    genre_ids: [18, 80],
    popularity: 490.5,
    number_of_seasons: 5,
    number_of_episodes: 62,
    tagline: 'Change the equation.',
    status: 'Ended',
  },
  {
    id: 119051,
    name: 'Wednesday',
    original_name: 'Wednesday',
    overview: 'A sleuthing, supernaturally infused mystery charting Wednesday Addams\' years as a student at Nevermore Academy.',
    poster_path: '/9PFonQ9516RgwmVz98R9vkKYJd6.jpg',
    backdrop_path: '/iHSwvFe7FdFFRmEN0IHwmqILSCY.jpg',
    media_type: 'tv',
    first_air_date: '2022-11-23',
    vote_average: 8.4,
    vote_count: 8500,
    genre_ids: [10765, 9648, 35],
    popularity: 380.0,
    number_of_seasons: 1,
    number_of_episodes: 8,
    tagline: 'Smart, sarcastic and a little dead inside.',
    status: 'Returning Series',
  },
  {
    id: 84958,
    name: 'Loki',
    original_name: 'Loki',
    overview: 'After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority (TVA), a bureaucratic organization that exists outside of time and space.',
    poster_path: '/voHUmluYmKyleukq9G63UtvKvNW.jpg',
    backdrop_path: '/r2t3Vq9o3nF0s7K9W7Fh8M2j7i9.jpg',
    media_type: 'tv',
    first_air_date: '2021-06-09',
    vote_average: 8.2,
    vote_count: 11200,
    genre_ids: [18, 10765],
    popularity: 340.0,
    number_of_seasons: 2,
    number_of_episodes: 12,
    tagline: 'Loki\'s time has come.',
    status: 'Ended',
  },
  {
    id: 106379,
    name: 'Fallout',
    original_name: 'Fallout',
    overview: 'The story of haves and have-nots in a world in which there’s almost nothing left to have. 200 years after the apocalypse, the gentle denizens of luxury fallout shelters are forced to return to the irradiated hellscape their ancestors left behind.',
    poster_path: '/AnsSKR9LuK0T9bAILJ3MGjh07JR.jpg',
    backdrop_path: '/5q1j1pWbCg2m6p4P7A7uD1K6M3O.jpg',
    media_type: 'tv',
    first_air_date: '2024-04-10',
    vote_average: 8.3,
    vote_count: 2300,
    genre_ids: [10765, 10759],
    popularity: 420.0,
    number_of_seasons: 1,
    number_of_episodes: 8,
    tagline: 'The end was only the beginning.',
    status: 'Returning Series',
  },
  {
    id: 76479,
    name: 'The Boys',
    original_name: 'The Boys',
    overview: 'A fun and irreverent take on what happens when superheroes—who are as popular as celebrities, as influential as politicians, and as revered as gods—abuse their superpowers rather than use them for good.',
    poster_path: '/2zmTngn1tYC1AvfnrFLhxeD82hz.jpg',
    backdrop_path: '/n5A7br2035n433hTf4dZ6Wk7W5g.jpg',
    media_type: 'tv',
    first_air_date: '2019-07-25',
    vote_average: 8.5,
    vote_count: 9800,
    genre_ids: [10765, 10759],
    popularity: 490.0,
    number_of_seasons: 4,
    number_of_episodes: 32,
    tagline: 'Never meet your heroes.',
    status: 'Returning Series',
  },
  {
    id: 126308,
    name: 'Shōgun',
    original_name: 'Shōgun',
    overview: 'In Japan in the year 1600, at the dawn of a century-defining civil war, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him, when a mysterious European ship is found stranded in a nearby fishing village.',
    poster_path: '/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg',
    backdrop_path: '/zW0v234buhsLzEG2yFvB4gqZ0J9.jpg',
    media_type: 'tv',
    first_air_date: '2024-02-27',
    vote_average: 8.5,
    vote_count: 1400,
    genre_ids: [18, 10768],
    popularity: 310.0,
    number_of_seasons: 1,
    number_of_episodes: 10,
    tagline: 'Dawn of a new era.',
    status: 'Returning Series',
  },
];

export function generateFallbackSeasons(tvShow: MediaItem): TVSeason[] {
  const seasonsCount = tvShow.number_of_seasons || 1;
  const seasons: TVSeason[] = [];

  for (let s = 1; s <= seasonsCount; s++) {
    const epCount = s === 1 ? (tvShow.number_of_episodes && tvShow.number_of_episodes < 12 ? tvShow.number_of_episodes : 8) : 8;
    const episodes: TVEpisode[] = [];
    for (let e = 1; e <= epCount; e++) {
      episodes.push({
        id: tvShow.id * 1000 + s * 100 + e,
        episode_number: e,
        season_number: s,
        name: `Chapter ${e}: ${getEpisodeTitle(tvShow.name || 'Episode', s, e)}`,
        overview: `In season ${s}, episode ${e}, key conflicts escalate as secrets come to light and characters confront their destinies in a thrilling installment.`,
        still_path: tvShow.backdrop_path,
        air_date: tvShow.first_air_date || '2023-01-01',
        vote_average: 8.0 + (e % 5) * 0.2,
        runtime: 45 + ((e * 7) % 20),
      });
    }

    seasons.push({
      id: tvShow.id * 100 + s,
      season_number: s,
      name: `Season ${s}`,
      overview: `Season ${s} of ${tvShow.name || 'the series'}.`,
      poster_path: tvShow.poster_path,
      episode_count: epCount,
      episodes,
    });
  }

  return seasons;
}

function getEpisodeTitle(showName: string, season: number, episode: number): string {
  const titles = [
    'The Beginning of the End',
    'The Vanishing Point',
    'Echoes of the Past',
    'Shadows in the Dark',
    'The Turning Tide',
    'Point of No Return',
    'Secrets in the Ashes',
    'The Final Stand',
    'Into the Unknown',
    'The Reckoning',
  ];
  return titles[(season * 3 + episode) % titles.length];
}
